openapi: 3.0.0
info:
    title: Simple Libray API
    description: This is an simple API REST developed using no-sql database.
    version: 1.0.0
servers:
    - url: http://localhost:3000
      description: Localhost nodejs server for dev purpose
paths:
    /signin:
        $ref: "paths/signin.yaml"
components:
    schemas:
        User:
            type: object
            properties:
                id:
                    type: integer
                    format: int64
                name:
                    type: string
                secondname:
                    type: string
                password:
                    type: string
                email:
                    type: string
            required:
                - name
                - secondname
                - email
                - password
        Book:
            type: object
            properties:
                id:
                    type: integer
                    format: int64
                author:
                    type: string
                title:
                    type: string
                description:
                    type: string
                isbn:
                    type: number
                image:
                    type: string
            required:
                - author
                - title
                - isbn
